### ISSUE TITLE
Automate video upload to YouTube so I can watch @ 2x

### ISSUE THREAD

**Issue by corysimmons** [H-Park/starcraft2ai#1]
Might help visualize how the AI learns.

**Comment by H-Park** [comment]
Please leave issues to code related things.

I enabled to archive broadcasts today, though I did that during the stream so I don't think today's stream was archived. 

I will definitely upload good results to YouTube once I have them.

**Comment by corysimmons** [comment]
>Please leave issues to code related things.

How much work should I do tracking you down to offer a suggestion vs how much work you have to do to read a couple sentences/close an issue?

**Comment by H-Park** [comment]
That's fair; I don't think my email is anywhere on twitch or github either... 

I was going to put content on YouTube once it becomes impressive enough to show (aka not running into the corner everytime), but I am still a long way from that.

I am also talking to 2 high ups in the SC2 esports scene that are really interested in getting this off the ground, so look for plugs to my agent at events in 2018.

**Comment by corysimmons** [comment]
>I was going to put content on YouTube once it becomes impressive enough to show (aka not running into the corner everytime), but I am still a long way from that.

I like watching it bump into corners and get better, and I know you're already speeding up the game as fast as possible. I just want to see it evolve even faster (at 2x) on YouTube, which I think would help visualize how it goes from bumping corners to absolutely wrecking everything.

Automating all Twitch streams to upload to YouTube (and being added to a playlist automatically) would be 👌. I'd make a bowl of popcorn and watch it learn from time-to-time. :^)

Really excited about this. Best of luck.
